[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version= '0.8.19'

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"
local = "http://localhost:8545"

[etherscan]
polygon = { key = "${POLYGONSCAN_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
