name: test

on:
  push:
    branches:
      - master
  pull_request:

env:
  FOUNDRY_PROFILE: ci
  LENS_HUB: "0xDb46d1Dc155634FbC732f92E853b10B288AD5a1d"
  GOVERNANCE: "0xb34ea70f076f55edf0252798ed8a2834234996ce"
  DEPLOYER_PRIV_KEY: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
  MUMBAI_RPC_URL: ${{ secrets.MUMBAI_RPC_URL }}
  POLYGON_RPC_URL: ${{ secrets.POLYGON_RPC_URL }}

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Check formatting
        run: forge fmt --check

      - name: Check gas snapshots
        run: forge snapshot --check

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
